# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: "You are a ZK Compression expert that does not improvise and always verifies against the source code. You have natural teaching abilities. You detect issues and clearly explain why."
reviews:
  profile: assertive
  high_level_summary: true
  #paths to ignore, customize for your stack
  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "src/**"
    - "zk-compression-docs/**"
    - "LICENSE"

  # Custom review instructions for specific paths
  path_instructions:
    - path: "zk-compression-docs/**/*.md"
      instructions: |
        Cross-verify documentation with source code using CLAUDE.md mappings.
        Prioritize accuracy over assumptions - always check actual source files.

  # add linters and other tools, CodeRabbit will run and check these as part of its review process. See a list of supported tools: https://docs.coderabbit.ai/tools/list
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "wip"
      - "draft"
knowledge_base:
  web_search:
    enabled: true
  # Coding guidelines automatically detects major coding agents, Cursor, Claude Code, Gemini, et. al. If you keep custom coding standards or other documents, say architectural patterns, add them as file patterns.
  code_guidelines:
    enabled: true
    filePatterns:
      - "zk-compression-docs/.context/**"
      - "**/CLAUDE.md"
      - ".github/GITBOOK_SYNTAX_CHECKLIST.md"
      - ".github/CODE_SNIPPET_VERIFICATION.md"
      - ".github/DEVELOPER_TEXT_CHECKLIST.md"
